<?php
$listCountry = Array
(
	'Australia',
	'Austria',
	'Azerbaijan',
	'Albania',
	'Algeria',
	'Angola',
	'Andorra',
	'Argentina',
	'Armenia',
	'Afghanistan',
	'Bahamas',
	'Bangladesh',
	'Barbados',
	'Bahrain',
	'Belarus',
	'Belize',
	'Belgium',
	'Benin',
	'Cote dIvoire',
	'Burma',
	'Bulgaria',
	'Bolivia',
	'Bosnia and Herzegovina',
	'Botswana',
	'Brazil',
	'Brunei',
	'Burkina Faso',
	'Burundi',
	'Bhutan',
	'Vanuatu',
	'Vatican City',
	'United Kingdom',
	'Hungary',
	'Venezuela',
	'East Timor',
	'Vietnam',
	'Gabon',
	'Guyana',
	'Haiti',
	'The Gambia',
	'Ghana',
	'Guatemala',
	'Guinea',
	'Guinea-Bissau',
	'Germany',
	'Honduras',
	'Grenada',
	'Greece',
	'Georgia',
	'Denmark',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'Egypt',
	'Zambia',
	'Zimbabwe',
	'Yemen',
	'Israel',
	'India',
	'Indonesia',
	'Jordan',
	'Iraq',
	'Iran',
	'Ireland',
	'Iceland',
	'Spain',
	'Italy',
	'Cape Verde',
	'Kazakhstan',
	'Cambodia',
	'Cambodia',
	'Cameroon',
	'Canada',
	'Qatar',
	'Kenya',
	'Cyprus',
	'Kyrgyzstan',
	'Kiribati',
	'China',
	'Comoros',
	'Congo',
	'Korea',
	'Costa Rica',
	'Cuba',
	'Kuwait',
	'Laos',
	'Latvia',
	'Lesotho',
	'Liberia',
	'Lebanon',
	'Libya',
	'Lithuania',
	'Liechtenstein',
	'Luxembourg',
	'Mauritius',
	'Mauritania',
	'Madagascar',
	'Macedonia',
	'Malawi',
	'Malaysia',
	'Mali',
	'Maldives',
	'Malta',
	'Morocco',
	'Marshall Islands',
	'Mexico',
	'Micronesia',
	'Mozambique',
	'Moldova',
	'Monaco',
	'Mongolia',
	'Namibia',
	'Nauru',
	'Nepal',
	'Niger',
	'Nigeria',
	'Netherlands',
	'Nicaragua',
	'New Zealand',
	'Norway',
	'United Arab Emirates',
	'Oman',
	'Pakistan',
	'Palau',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Poland',
	'Portugal',
	'Russia',
	'Rwanda',
	'Romania',
	'El Salvador',
	'Samoa',
	'San Marino',
	'Sao Tome and Principe',
	'Saudi Arabia',
	'Swaziland',
	'North Korea',
	'Seychelles',
	'Senegal',
	'Saint Vincent and the Grenadines',
	'Saint Kitts and Nevis',
	'Saint Lucia',
	'Serbia',
	'Singapore',
	'Syria',
	'Slovakia',
	'Slovenia',
	'United States of America',
	'Solomon Islands',
	'Somalia',
	'Sudan',
	'Suriname',
	'Sierra Leone',
	'Tajikistan',
	'Thailand',
	'Tanzania',
	'Togo',
	'Tonga',
	'Trinidad and Tobago',
	'Tuvalu',
	'Tunisia',
	'Turkmenistan',
	'Turkey',
	'Uganda',
	'Uzbekistan',
	'Ukraine',
	'Uruguay',
	'Fiji',
	'Philippines',
	'Finland',
	'France',
	'Croatia',
	'Central African Republic',
	'Chad',
	'Montenegro',
	'Czech Republic',
	'Chile',
	'Switzerland',
	'Sweden',
	'Sri Lanka',
	'Ecuador',
	'Equatorial Guinea',
	'Eritrea',
	'Estonia',
	'Ethiopia',
	'South Africa',
	'South Korea',
	'Jamaica',
	'Japan',
	'Австралия',
	'Австрия',
	'Азербайджан',
	'Албания',
	'Алжир',
	'Ангола',
	'Андорра',
	'Аргентина',
	'Армения',
	'Афганистан',
	'Багамские острова',
	'Бангладеш',
	'Барбадос',
	'Бахрейн',
	'Беларусь',
	'Белиз',
	'Бельгия',
	'Бенин',
	'Берег Слоновой Кости',
	'Бирма',
	'Болгария',
	'Боливия',
	'Босния и Герцеговина',
	'Ботсвана',
	'Бразилия',
	'Бруней',
	'Буркина-Фасо',
	'Бурунди',
	'Бутан',
	'Вануату',
	'Ватикан',
	'Великобритания',
	'Венгрия',
	'Венесуэла',
	'Восточный Тимор',
	'Вьетнам',
	'Габон',
	'Гайана',
	'Гаити',
	'Гамбия',
	'Гана',
	'Гватемала',
	'Гвинея',
	'Гвинея-Бисау',
	'Германия',
	'Гондурас',
	'Гренада',
	'Греция',
	'Грузия',
	'Дания',
	'Джибути',
	'Доминика',
	'Доминиканская Республика',
	'Египет',
	'Замбия',
	'Зимбабве',
	'Йемен',
	'Израиль',
	'Индия',
	'Индонезия',
	'Иордания',
	'Ирак',
	'Иран',
	'Ирландия',
	'Исландия',
	'Испания',
	'Италия',
	'Кабо-Верде',
	'Казахстан',
	'Камбоджа',
	'Камбоджа',
	'Камерун',
	'Канада',
	'Катар',
	'Кения',
	'Кипр',
	'Киргизия',
	'Кирибати',
	'Китай',
	'Коморские острова',
	'Конго',
	'Корея',
	'Коста-Рика',
	'Куба',
	'Кувейт',
	'Лаос',
	'Латвия',
	'Лесото',
	'Либерия',
	'Ливан',
	'Ливия',
	'Литва',
	'Лихтенштейн',
	'Люксембург',
	'Маврикий',
	'Мавритания',
	'Мадагаскар',
	'Македония',
	'Малави',
	'Малайзия',
	'Мали',
	'Мальдивы',
	'Мальта',
	'Марокко',
	'Маршалловы острова',
	'Мексика',
	'Микронезия',
	'Мозамбик',
	'Молдова',
	'Монако',
	'Монголия',
	'Намибия',
	'Науру',
	'Непал',
	'Нигер',
	'Нигерия',
	'Нидерланды',
	'Никарагуа',
	'Новая Зеландия',
	'Норвегия',
	'Объединенные Арабские Эмираты',
	'Оман',
	'Пакистан',
	'Палау',
	'Панама',
	'Папуа-Новая Гвинея',
	'Парагвай',
	'Перу',
	'Польша',
	'Португалия',
	'Россия',
	'Руанда',
	'Румыния',
	'Сальвадор',
	'Самоа',
	'Сан - Марино',
	'Сан-Томе и Принсипи',
	'Саудовская Аравия',
	'Свазиленд',
	'Северная Корея',
	'Сейшельские острова',
	'Сенегал',
	'Сент-Винсент и Гренадины',
	'Сент-Китс и Невис',
	'Сент-Люсия',
	'Сербии',
	'Сингапур',
	'Сирия',
	'Словакия',
	'Словения',
	'Соединенные Штаты Америки',
	'Соломоновы острова',
	'Сомали',
	'Судан',
	'Суринам',
	'Сьерра-Леоне',
	'Таджикистан',
	'Таиланд',
	'Танзания',
	'Того',
	'Тонга',
	'Тринидад и Тобаго',
	'Тувалу',
	'Тунис',
	'Туркменистан',
	'Турция',
	'Уганда',
	'Узбекистан',
	'Украина',
	'Уругвай',
	'Фиджи',
	'Филиппины',
	'Финляндия',
	'Франция',
	'Хорватия',
	'Центрально-Африканская Республика',
	'Чад',
	'Черногория',
	'Чешская республика',
	'Чили',
	'Швейцария',
	'Швеция',
	'Шри Ланка',
	'Эквадор',
	'Экваториальная Гвинея',
	'Эритрее',
	'Эстония',
	'Эфиопия',
	'ЮАР',
	'Южная Корея',
	'Ямайка',
	'Япония',
);
?>